### ISSUE TITLE
How do i use it?

### ISSUE THREAD

**Issue by melxman** [vit9696/Lilu#1]
This new kext, only auxiliary applealc realize sound card patch? Or can all kextpatch be implemented? If it is the latter, how do i do it?

**Comment by vit9696** [comment]
It is the latter. Follow the smaller examples (e.g. IntelGraphicsFixup) and read the documentation provided in the headers to understand how to develop Lilu plugins.

I could answer definite questions if any, but there should be a reason to create Lilu plugin instead of using e.g. your bootloader's patcher.
