### ISSUE TITLE
Lilu is making longer my boot time

### ISSUE THREAD

**Issue by Szczepancio** [vit9696/Lilu#14]
"Lilu: patcher @ lookup patching applied only 0u patches out of 2u"
This error I get at my desktop PC about 100 times at verbose boot.
I use iGPU trick to boot (rx480) so maybe this is fault because its eats some of RAM and Lilu don't know where to patch?
On my laptop it works without an harm.

**Comment by vit9696** [comment]
This message appears when some kext (not Lilu but some plugin e.g. AppleALC) tries to apply a patches, but fails to find some of them. It is best to find the relevant plugin and report this issue there.
Most likely you mixed clover kext patches with Lilu plugin patches somewhere.

As for Lilu I might hide this message for non-debug output because technically even if something is not patched, it may not be an actual issue.
