### ISSUE TITLE
Suggestion for USB plugin

### ISSUE THREAD

**Issue by malhal** [vit9696/Lilu#18]
Hi I use the graphics and audio plugins which are excellent but USB is still a pain point for me so I have a suggestion for a USB plugin which could really help people. For example, my hack would crash on sleep until I limited to 14 ports with a SSDT, which I generated with a script I found on GitHub however it isn't supported and has a bug with 13 instead of 14 ports being enabled so missing 1. Also running the script again requires making a decision about every port rather than just making a change, requiring cross-referencing every port ID with my notes.

A USB kext plugin could be packaged as an installer pkg. When ran it could scan ioreg for USB ports and then writes them to clover/kexts/others/USBPorts.plist with an array and a bool for each one for on or off. By default the first 14 Ports are on. Each port would also have a description field which the user can edit to  a note to identify the port like lower left USB 3. And it also installed the USBPorts.kext to the same dir. So now to change the ports that are enabled, say I move a device from one internal usb header to another, it's just a case of editing the plist and rebooting. The design of the kext is to check the plist for the port config and only enable the ones that are marked on, up to a limit of 14.

Maybe also we can share the USBPorts plist for each motherboard so the users can get a config plist with the description fields pre-filled to help them with quickly enabling the ports they want. The model of motherboard will be a top level item in the plist. These could all be bundled with the installer and then the user could choose their board from a list, unless there is an ID that could be used to automatically identify it.

What do you think?

**Comment by vit9696** [comment]
Hi,

The actual problem with usb is that limit of 14 ports, which is quite artificial. Unfortunately you cannot patch it with Lilu due to the time XHC kext loads, so you either have to write a plist-only kext with specific ports to use or perform binary patching to increase the limit.

Without making a patch that unlocks all the ports you cannot really determine which ports need to be used, and thus you cannot really automate this project. In fact in most cases you even have to manually try each port. Due to a large amount of motherboards and different revisions of each motherboard a database would also not work well enough.

Even though your intentions might be nice in theory in practice it is not really doable. Sorry.
