### ISSUE TITLE
Lilu.kext + High Sierra plus enabled QuickSync --> iTunes crashes

### ISSUE THREAD

**Issue by elmacci** [vit9696/Lilu#20]
Dear vit9696,

may I kindly point you to this thread regarding lilu, high sierra and itunes crashes on tonymac?
https://www.tonymacx86.com/threads/itunes-12-7-constantly-crashing-random-messages.233135/

In short:
Hackintosh-Setups with connectorless IGPU + ded. GPU (Nvidia) configured to enable Intel QuickSync are experiencing iTunes crashes (VDADecoder?) when using Lilu.kext (1.17 and 1.20) under high sierra. 

Current workaround:
Deleting Lilu.kext (both itunes and QuickSync work) or using boot arg shikigva=1 (iTunes working again, but no QuickSync).

I am just wondering if it is even related to lilu - if not, never mind ;)

cheers

**Comment by vit9696** [comment]
Hi,

I did hear of the issue, but I am yet to upgrade to 10.13 and see it myself sooner or later. So far all the tests showed that iTunes continues to crash even without Lilu, and it is a bit surprising your report is different.

Now to think of it, it may be related to https://github.com/vit9696/Shiki/issues/9, which means the driving force is _might_ be Shiki. While it is very unlikely, there always is a slight possibility my code is involved directly or indirectly, if you or anybody else have some free time, could you please perform a *clean* installation without Shiki. I.e. Shiki.kext should never be loaded on the OS, and see if you get any iTunes crashes.

In addition to that I ask you to use the latest Lilu compiled from source. If iTunes is nominal, then I ask you to install Shiki.kext and see if anything changes.

Thanks

**Comment by elmacci** [comment]
Thank you for your quick response.
Clean Install = Full System Disk Wipe? Thought Lilu (&Shiki) don't perform permanent changes to system files?
However, will try that on the weekend.

I did not yet compile a fresh lilu from source. That is something I will try tonight and report back.

**Comment by vit9696** [comment]
Neither Lilu, nor Shiki should perform any permanent changes to system files. Yet after I received the report I mentioned above I accept the unlikely possibility that 10.13 could have changed something internally, and there could a compatibility issue in this area.

**Comment by familygw** [comment]
Hi,
I've done this tests:
SystemDef: iMac15,1 -  CPU i7 4790K - GPU: nVidia GTX 750ti.

[Scenario 1]
Kexts:
- No Shiki, Lilu, AppleALC, CodecCommander and NvidiaGraphicsFixup.
- AppleHDA patched using Toleda's script.
- Blackscreen patched manually modifying the info.plist of AppleGraphicsPolicy.kext.

Results:
- Hardware EncSupport: No
- iTunes works fine. AirPlay works fine.
- DRM videos, doesn't work.
- Previously downloaded movies on iTunes causes system freezes (need to shutdown the PC).

[Scenario 2]
Kexts:
- Lilu 1.1.7 installed.
- AppleALC 1.1.4 installed.
- NvidiaGraphicsFixup 1.1.3 installed.
- No Shiki

Results:
- Hardware EncSupport: No
- iTunes works fine. AirPlay works fine.
- DRM videos, doesn't work.
- Previously downloaded movies on iTunes causes system freezes (need to shutdown the PC).

[Scenario 3]
Kexts:
- Lilu 1.1.7 installed.
- AppleALC 1.1.4 installed.
- NvidiaGraphicsFixup 1.1.3 installed.
- Shiki 2.0.5 installed.

Results:
- Hardware EncSupport: yes
- iTunes crashes. AirPlay works fine.
- DRM videos works ok.
- Previously downloaded movies on iTunes works ok.

[Scenario 4]
Kexts:
- Lilu 1.1.7 installed.
- AppleALC 1.1.4 installed.
- NvidiaGraphicsFixup 1.1.3 installed.
- Shiki 2.0.5 installed.
- Bootarg: shikigva=1

Results:
- Hardware Acceleration: no
- iTunes crashes. AirPlay works fine.
- DRM videos works ok.
- Previously downloaded movies on iTunes works ok.


Same results with the compiled versions of Lilu, AppleALC and NvidiaGraphicsFixup from the latest sources.
If I use the latest code for Shiki, even using the bootarg shikigva=1 or shikigva=4, I've iTunes crashes (see the attachment), even I have the Hardware EncSupport enabled, I assume that is happen because the latest commit on the code have "Added hardware video decoding fix for SKL/KBL & NVIDIA (`shikigva=4`)"

Hope this tests helps.
[itunes_crash.txt](https://github.com/vit9696/Lilu/files/1356977/itunes_crash.txt)

**Comment by vit9696** [comment]
Hi,

Thank you for such a detailed output. Firstly, may I clarify what you mean under hardware encsupport? Does that mean hardware video encoding? Asking because hardware encoding works out of the box in most cases, what is more problematic is hardware decoding.

Unfortunately, after inspecting the log I am afraid I will be of no help. Judging from your crash log I am afraid the issue is about hardware acceleration causing incompatibilities/bugs existent in Apple's  and NVIDIA code. If it was due to Shiki/Lilu, there would have been codesign/amfid messages in the log, and here the crash is a selector call on an invalid object, a part I do not touch at all.

You can prove it rather easily. Take "Scenario 2" but change your mac model to iMac14,2. This will make hardware video decoding/encoding work without Shiki, and you will start getting iTunes crashes. If you still have any suspect on Lilu and friends afterwards, you could also remove NvidiaGraphicsFixup and replace it with a plist-only kext (commonly referred as iMac.kext).

**Comment by familygw** [comment]
For Hardware EncSupport I meaning about Quick Sync (Hardware Encoding, maybe I'm mixing names), see the attached screenshoot for more reference (taken from the macx video converter).

![captura de pantalla 2017-10-04 a la s 15 55 27](https://user-images.githubusercontent.com/670078/31194136-95ecf812-a91c-11e7-82cf-85b20cc77bbb.png)

With a sysdef 14,1 and the kexts of the scenario 2, I have not the 'Hardware Encoding Supported' (see the second attachment. iTunes doesn't crash neither.
![captura de pantalla 2017-10-04 a la s 16 10 09](https://user-images.githubusercontent.com/670078/31194766-8e5cfe24-a91e-11e7-96b6-0edd53d048e2.png)

I'm trying to build a USB media to make a clean install and try again.

Any other thing that I can do to verify this cases, and help to confirm or discard the issue?

Thanks in advance!

**Comment by vit9696** [comment]
You could test with [VDADecoderChecker](https://applelife.ru/threads/shiki-proigryvanie-zaschischjonnogo-kontenta-na-raznom-oborudovanii.1349123/page-26#post-647746). It provides somewhat more descriptive output. Please let me know what you see in it.

I just realised that since you have Devil's Canyon CPU (i.e. not Haswell), you might not have an ability to run hardware decoding/encoding without applying the patches, ugh…. 

A good idea is to verify file integrity after testing with Lilu/Shiki enabled. I.e. take a clean OS, calculate file hashes via shasum:
```
shasum /System/Library/PrivateFrameworks/AppleGVA.framework/Versions/A/AppleGVA 
shasum /System/Library/PrivateFrameworks/CoreFP.framework/Versions/A/CoreFP
shasum /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
```
Save this somewhere. Then after running a test with Shiki/Lilu on, you boot with them both disabled or removed and recalculate again. The hashes should match.

**Comment by vit9696** [comment]
In fact, I have just realised that "Scenario 2" is the one with old kexts. Try with 14,2 and new kexts (i.e. compiled from source). Without the latest changes in NvidiaGraphicsFixup you won't have IOVARendererID injected.

**Comment by familygw** [comment]
Welll, with the sysdef 14,2 and the latest kexts (with the r13 for NvidiaGraphicsFixup) have the same problem.

See the errors from iTunes (they are random).
As far I could check, the hashes match in all the cases (with or without the kexts loaded, different sysdef, etc.).

I'm repopulating the outputs from VDADecoderChecker.

**Comment by familygw** [comment]
Well... after a time doing tests this is the results of VDADecoderChecker:

Without iMac.kext (with any sysdef and with any kext combination):
VDADecoderCreate failed. err: -12473
An error was returned by the decoder layer. This may happen for example because of bitstream/data errors during a decode operation. This error may also be returned from VDADecoderCreate when hardware decoder resources are available on the system but currently in use by another process.
VDADecoderCreate failed. err: -12473

With iMac.kext:
2017-10-04 21:09:34.429911-0300 VDADecoderChecker[542:4919] GVA error: AGPMGetManagedPortForAccelerator returned 0x4 for VP4
GVA info: Successfully connected to the Intel plugin, offline Gen75 
Hardware acceleration is fully supported
Program ended with exit code: 0

With iMac.kext and with bootarg shikigva=1 (obviously):
VDADecoderCreate failed. err: -12473
An error was returned by the decoder layer. This may happen for example because of bitstream/data errors during a decode operation. This error may also be returned from VDADecoderCreate when hardware decoder resources are available on the system but currently in use by another process.
VDADecoderCreate failed. err: -12473

iTunes: still crashing in the already mentioned cases.

**Comment by vit9696** [comment]
@familygw okay, did I get you correctly that if you:
- do not use Shiki
- have iMac.kext
- have iMac14,2 model
- use Lilu only for kext patching (e.g. you only have AppleALC / NvidiaGraphicsFixup)

You get:
- Hardware acceleration is fully supported in VDADecoderChecker
- iTunes crashes

If this is correct, then I am afraid it concludes that iTunes crashes are unrelated to Lilu/Shiki.

**Comment by elmacci** [comment]
Hello all,

you're feedback made me investigate the scenario further where quicksync is enabled and lilu/shiki are not loaded and itunes does not crash.

After more intensive testing, I have to apologize for leading you to a false assumption, i.e. lilu/shiki might be the culprit.

It is obviously not.
I found that with quicksync enabled and without lilu/shiki, itunes does not crash instantly, but it does crash after several times of opening and closing. Because it happended instantly when lilu/shiki where loaded, and NOT instantly wshen Lilu/shiki are not loaded, i was under the false assumption that it might be related to lilu/shiki. Bugger. Sorry for that and the time you invested!

So, we are back to square one unfortunately.

I do not understand why the same configuration which worked perfectly under sierra does suddenly not work under high sierra. Obviously Apple changed something under the hood which lets itunes crash on hackintoshes - but not on genuine macs (i have cloned my hackintosh macOS to my genuine macbook, same os, same itunes etc. --> no crashes).

As genuine macs dont suffer from this issue, I dont think we can expect a bug fix from apple.

I'd really love to know what exactly might be the culprit here. But realizing that Lilu/shiki is not the issue, this thread can be closed IMHO. 

Thank you for your time!
cheers

**Comment by vit9696** [comment]
Genuine macs with nvidia also have problems, just they may not have crashes but actually freezes, for example https://applelife.ru/threads/shiki-proigryvanie-zaschischjonnogo-kontenta-na-raznom-oborudovanii.1349123/page-35#post-682785. It is also worth checking MacPro5,1 since it has a software drm decoder, and on most other real macs we have a hardware drm decoder.

If Apple does not fix it with time I might debug this, but only when I upgrade to 10.13.

**Comment by Dids** [comment]
FYI, I was also seeing this, but repairing permissions as stated here fixed it, although not entirely sure why: https://support.apple.com/en-us/HT203538

**Comment by Dids** [comment]
I figured out a temporary fix for this issue. I can reproduce it 100% of the time.

1. `killall -9 com.apple.iTunesLibraryService`
2. `sudo rm -rf /Users/Shared/SC\ Info`
3. Start iTunes and it's 100% stable
4. Completely close and reopen iTunes and it's crashing again, until you run the steps 1-3 again
