### ISSUE TITLE
Lilu v1.2 causes Kernel Panic in ElCapitan & Mavericks 

### ISSUE THREAD

**Issue by vinvilli** [vit9696/Lilu#26]
The Lilu kext v1.2 causing KP in ElCapitan & Mavericks but its working well in previous versions

**Comment by 07151129** [comment]
Can you provide the relevant panic reports?

**Comment by piiiggg** [comment]
Happen with me too, I'm using High Sierra and still didn't know what happened with my hackintosh. Using macOS 10.13

**Comment by tengg** [comment]
Same here on 10.13. 
Reverted back to 1.17.
The kp was too fast to make take a shot.

**Comment by vit9696** [comment]
The issue is most likely corrupted kextcache. You should not receive a kernel panic even in such a case, but at the moment I cannot debug this issue since it does not reproduce.
As a workaround you could boot with `-lilulowmem` or (which is more desired) boot into recovery and use kextcache utility to rebuild the kext cache.

**Comment by piiiggg** [comment]
You are right, I try to rebuild kextcache yesterday and getting bootloop again. But no kernel panic, just something about bootcache.playlist. I'm able to boot with UseKernelCache=No

**Comment by vit9696** [comment]
UseKernelCache=No? Are you using Chameleon bootloader? It is nice that we found a workaround at least.

**Comment by piiiggg** [comment]
@vit9696 No I'm using Clover, I just found out that UseKernelCache=No not working anymore. I have to use recovery/terminal and use this command `sudo kextcache -i /Volumes/"macOS partition name"`

**Comment by stickpin** [comment]
I have the same issue. I don't think it's related to FakeSMC.kext. I'm running version 6.26.1440 for quite a long time now. The only thing that changed from my end, was Lilu.kext with AppleALC.kext version 1.2.0.

@piiiggg which FakeSMC.kext version you using?

@vit9696 if you need some help with debugging, compile some special version with deep logging that will help you to analyze the issue and I will run it until I will catch this issue again. I think you are right and it's somehow related to kextcache, because the issue is not reproducible all the time. I can run with version 1.2.0 for few days and then it happens again.

I'm running latest Clover 4259 + 10.13.

**Comment by vit9696** [comment]
@stickpin, there is not much you can do even with the debug prints. The issue is more or less known to me, when Lilu is asked to patch a kext it is no longer is present at this address. Since kext memory is wired, I could imagine the only two possible reasons: it is either relocated or unloaded. Even if I add the prints they will not really answer why it happens.

My best guess there is something broken in the system, so the kextcache becomes invalid in the first place and it cannot be rebuilt while the system is running before reboot/shutdown. Because normally you cannot shutdown/reboot macOS without getting the right kextcache in the first place.

Tell me, how you *all* use your computer normally and what are the usual preconditions before the crash. Also I need all the info about your hardware/software from macmodel/non apple kexts installed and cpu/nvram type to applied stuff "I usually use VMware to run Windows VMs and power off the computer by cutting the power".

The thing is, however, even if could reproduce this the solution will most likely be to avoid a kernel panic, but the real issue (e.g. some system kext is probably unloaded like AppleHDA) will not be fixed, because it is the issue of your hack installation.

**Comment by piiiggg** [comment]
@stickpin It's related to FakeSMC.kext, I used the Oct version. So I downgrade to June version and rebuild kextcache using recovery. Now I have no any problem, or maybe it didn't happen yet but I will update if I have something

**Comment by piiiggg** [comment]
@vit9696 I have to reinstall my OS 3 times because of this issue, the first time I just create a Time Machine partition and use it like normal. So the next reboot my hack is fully dead. The second time, I didn't do anything. Just boot up and use some Chrome and iTunes, next reboot is dead too. As I found on `-v` log, I got this message `BootCacheControl: Unable to open /var/db/BootCache.playlist: 2 No such file or directory.` I didn't notice this line at the first and second time because I though it was kp.

**Comment by vit9696** [comment]
This should be fixed if you compile the latest Lilu from source.

**Comment by tengg** [comment]
@vit9696  Just curious why it would make a different if building from source, instead of using the pre-built one? Different SDK?

**Comment by vit9696** [comment]
Latest means not 1.2.0 but 1.2.1 from git.

**Comment by piiiggg** [comment]
@tengg He applies some commit to fix it but he has no time to compile into .kext file so if you want to use latest version you can compile by yourself
