### ISSUE TITLE
10.12.5 LILU results in kernel panic

### ISSUE THREAD

**Issue by wmchris** [vit9696/Lilu#3]
Hi,
i got a nasty kernel panic on 10.12.5 with LILU.kext as reason. screen got full of LILU error messages before the KP. forgot to write down the exact error :-(

**Comment by vit9696** [comment]
Well, and what am I supposed to do with this? Come back when you get more information.

**Comment by wmchris** [comment]
Well its easily reproducable. Boot OSX 10.12.5 with Lilu kext...

**Comment by vit9696** [comment]
Maybe for you but not for hundreds of other people who use 10.12.5 since beta days and have no isses.

**Comment by Dids** [comment]
Yeah, running 10.12.5 with the latest Lilu.kext myself, and it's working perfectly fine.

**Comment by wmchris** [comment]
strange, i had this issue on 3 different machines.

**Comment by erikwestlund** [comment]
No issue on two separate machines for me.
Z87 and X99

**Comment by Dids** [comment]
@wmchris Actually, I've now been seeing issues for the past two days, and specifically with the latest Lilu.kext.

I figured it was random at first, because somehow Lilu.kext is first not being loaded properly (causing no signal, KP etc.), but then the kext itself becomes corrupt on the filesystem, so I have to repair both the disk partition map and the volume (EFI in my case, since I store my kexts there).

This has happened two mornings in a row now, so not sure if it's caused by simply rebooting, or by booting to Windows (through Clover) and then back to macOS.

This may or may not end up being related to Lilu.kext, but it is the only file that keeps ending corrupted, which then breaks AppleALC/NvidiaGraphicsFixup.

**Comment by vit9696** [comment]
Well, it is great that some of you have certain mysterious kernel panics (including https://github.com/vit9696/Shiki/issues/6) but all you do is spamming in my mailbox with unhelpful messages. Look, if you want anything to be improved, there need to be logs, callstacks, all the kexts involved, configuration, etc. etc.

EFI partition generally gets broken when you have something writing to it from EFI, so watch out for clover logging or something alike, it is very unlikely that Lilu is in charge of it.

You could also verify the order clover injects the kexts in, it should not be relevant since there are proper dependency rules in them, but I could imagine clover/boot.efi violating them. If it is doing weird things, consider contributing some kext loading order configuration to clover.

**Comment by wmchris** [comment]
not sure, but i think i had lilu in S/L/E on my old installation and it did KP.
