### ISSUE TITLE
macOS upgrade 10.13.4 Beta fails with Lilu.kext and IntelGraphicsFixup.kext

### ISSUE THREAD

**Issue by Piker-Alpha** [vit9696/Lilu#31]
The upgrade to macOS 10.13.4 Beta failed (black screen) with Lilu.kext IntelGraphicsFixup.kext.

This is the debug output that I see:
<pre>
Lilu:  config @ (DBG) init via mac_count_check_remount
Lilu:   iokit @ (DBG) missing OSPrelinkKextCount property!
Lilu: patcher @ (DBG) got 1 relink error and 0 kernel id
Lilu:    mach @ (DBG) MachInfo asKernel 1 object constructed
Lilu:    mach @ (DBG) couldn't find a suitable executable
Lilu: patcher @ failed to ini MachInfo for kernel
Lilu: patcher @ (DBG) got 1 relink error and 0 kernel id
Lilu:  config @ (DBG) failed to initialise kernel patcher
</pre>
Is this perhaps related to the changes that were made to get rid of the prelinkedkernel message?

Used boot arguments: -v -lilubeta -liludbg -igfxbeta -no-zp debug=0x12a -rootdmg-ramdisk auth-root-dmg=file:///macOS%20Install%20Data/BaseSystem.dmg

p.s. I boot without a prelinkedkernel

**Comment by vit9696** [comment]
Hi, it looks like the kernel is somewhere in an unexpected place. It successfully finds one of the prelinkKernelPaths but later fails to load it, because it is a normal kernel, not a prelinked one. And then then when it looks for a normal kernel it finds no such file. (See 
https://github.com/vit9696/Lilu/blob/master/Lilu/Headers/kern_patcher.hpp#L379).

Could you tell me which kernel is actually used? Did Apple move the kernel somewhere else or did you do anything special?

**Comment by Piker-Alpha** [comment]
No. I didn't do anything special.

There is no: /System/Library/Kernels directory in a BaseSystem.dmg and never was.

What about using the one in memory? note that the kernel is already loaded. Or perhaps extract the kernel from the relinked kernel?

**Comment by vit9696** [comment]
The one in memory may not be used, because it has symbol table stripped.
As for the path you mentioned it is exactly my lack of knowledge. Does adding it to prelinkKernelPaths fix the issue?
If so, I will commit it to master. By the way, may you be aware of any other paths that were not taken into the account? I could think of a custom kcsuffix, (currently debug and development kernels are hardcoded, should fix this), but I do not know about any other paths.

**Comment by vit9696** [comment]
I checked some details and additionally added the recovery path.
Let me know if https://github.com/vit9696/Lilu/commit/64d82e0b6cfbb39c3539d760a40971c790d6942c fixes the issues for you.

**Comment by BarbaraPalvin** [comment]
can you consider more case? like fusion drive
el capitan
\\com.apple.boot.S\\System\\Library\\PrelinkedKernels\prelinkedkernel
sierra+
\\com.apple.boot.R\\prelinkedkernel

**Comment by vit9696** [comment]
Hi, I am not sure that they are necessary, since there always is the kernel in Kernels, unlike recovery. And prelinked is naturally relevant mostly in the recovery. Do you have a Fusion Drive to test if adding the paths here: https://github.com/vit9696/Lilu/blob/master/Lilu/Headers/kern_patcher.hpp#L379 changes anything?

**Comment by BarbaraPalvin** [comment]
because this cases 1st stage after update from appstore
"/macOS Install Data/Locked Files/Boot Files/prelinkedkernel",

like this,  this case also 1st stage after update from appstore for fusion drive
el capitan
\com.apple.boot.S\System\Library\PrelinkedKernels\prelinkedkernel
sierra+
\com.apple.boot.R\prelinkedkernel

i will ask this to fusion drive user

**Comment by BarbaraPalvin** [comment]
last commit 1.2.2. i got kp. i can't correctly catch it. because log is flood and ended up to report apple.

**Comment by vit9696** [comment]
Ok, sorry, was in a hurry yesterday and left a few mistakes. I committed a fix and included the paths you mentioned. Please test that and let me know if it works/does not with and without the new paths on a fusion drive system.

**Comment by BarbaraPalvin** [comment]
sorry for late reply.
i tested it with location. boot and feature are no problem.
i'm also think "I have a strong suspect they are not necessary". not sure whether need it.
just pike mentioned beta4 case for usage. if it needs for other boot loader or any.
if you interested in location of prelinkedkernel, check this,
https://sourceforge.net/p/cloverefiboot/code/4320/tree//rEFIt_UEFI/Platform/Settings.c#l7150

now, 1.2.2 is great. thanks

**Comment by vit9696** [comment]
@BarbaraPalvin Mm, I am afraid I will have to ask you do more tests, otherwise it will be pretty problematic:
1. Find a FusionDrive machine and try booting with and without [these two lines](https://github.com/vit9696/Lilu/blob/master/Lilu/Headers/kern_patcher.hpp#L386), note that you will have to replace 6 with 4.
2. Lilu is designed to support 10.8 and newer, and I am pretty certain it worked in the installer for me for at least 10.8 and 10.12 not so long ago without anything from [this list](https://sourceforge.net/p/cloverefiboot/code/4320/tree//rEFIt_UEFI/Platform/Settings.c#l7164). Could you check if different installers work fine without anything added?

@Piker-Alpha is your issued with 10.13 resolved with [this line](https://github.com/vit9696/Lilu/blob/master/Lilu/Headers/kern_patcher.hpp#L385) added? Do you think all the other paths for installers will now be needed (now that caches are rejected when no kernelcache is used)?

**Comment by BarbaraPalvin** [comment]
@vit9696 
yes. like you said, it's no problem. i successed to boot 10.13.4 beta4 with 1.2.1. 
it's start after pike mentioned. i'm not sure whether it needs. during 3 days, i spent times to improve clover in old osx.
at least, in clover, seems no need.
i will ask test with both kext(without 2 lines or with) to fusion drive user. 
always thank you for amazing work.

**Comment by BarbaraPalvin** [comment]
@vit9696 
Fusion Drive user did not report lilu(prelinkedkernel 2line)
i don't have opportunity for fusion drive.
i think it doesn't matter 2line to use macOS in clover. i don't know other bootloader.
latest commits is good. thank you so much

**Comment by vit9696** [comment]
Let's leave it as is then.

@Piker-Alpha I assume it works for you too.
