### ISSUE TITLE
New Plugin: AzulPatcher4600

### ISSUE THREAD

**Issue by coderobe** [vit9696/Lilu#5]
This kext fixes a new issue (since 10.12.4) with the mobile HD4600 which, on some systems, causes the system to be unresponsive for an arbitrary timeframe after boot, as an added bonus this makes displays attached to HDMI initialize earlier because of the nature of the patch.
It also patches HDMI audio to work properly because it's sorta related.

Repo: https://github.com/coderobe/AzulPatcher4600

**Comment by vit9696** [comment]
Hi, thanks for your research. We already have something for Intel HD graphics, perhaps it is best to keep things in one place?
Your patch does not have apple logo/pavp fixes, which still need to be applied, and IntelGraphicsFixup has no fixes you made. Might it be a better idea to merge all your changes into IntelGraphicsFixup, since it is larger/more general? Thanks!

**Comment by coderobe** [comment]
I thought about it, but without additional hardware checks this wouldn't work out. This patch will most certainly only work on mobile haswells afaik. Some systems might even require a slightly modified version of the patch to work correctly, because of different connector topology.

So without a huge rewrite with proper HW checking & more tests on different hardware i really wouldn't want this to be in IntelGraphicsFixup for now.

This is a kind of niche patch in that sense.

**Comment by coderobe** [comment]
I'm all for implementing more patches for different setups, but i'd have to come up with a way to reliably figure out the topology of the ports - automatically.

**Comment by vit9696** [comment]
There is some example code on how to detect the hardware in AppleALC, could use it as a base? There also is mobile/desktop detector, but I think device-id should be enough.
As for HDMI fixes, maybe it is best to put them into AppleALC, after all it is designed for audio patches?
As for ports, I am unaware what happens there, but would not they be the same amongst one device-id?

Could temporarily add your work to the list though, so that people could find it until you make a better solution?

**Comment by coderobe** [comment]
I will take a look at AppleALC's HW detection, thanks for the info.

I'm gonna look into submitting a PR to AppleALC regarding the HDMI fix as well - sounds like a great idea!
And the ports do not seem to be the same. It depends on how the laptop vendor connects them. The mobile hd4600 appears to have 3 ports, but most vendors connect 2 (internal display & 1 hdmi/dp port) and it's up to them on which to connect. This disables the DP port, which appears to be the least frequently used one, but it heavily depends on the laptop model - and i wouldn't know which vendor/model does what to cover even a small fraction of every haswell laptop out there 😉 

In the end it's up to you whether to include this kext to the plugin list or not - it might be useful for people with this setup though, so why not?

**Comment by vit9696** [comment]
Hmm, given this situation I feel that the best idea will be to add a boot argument to IntelGraphicsFixup to decide which port to patch. This way will be flexible, and we will not have to deal with extra code requirements. What do you think?
