### ISSUE TITLE
New Plugin: TrimForce

### ISSUE THREAD

**Issue by coderobe** [vit9696/Lilu#7]
This plugin forces SSD TRIM support on "non-supported" drives

link: https://github.com/coderobe/TrimForce

note: this might even be useful for real macs

**Comment by vandroiy2013** [comment]
Why not use sudo trimforce enable?

**Comment by corpnewt** [comment]
Because that causes exceptions when rebuilding kext cache - and forces you to disable SIP

**Comment by vandroiy2013** [comment]
Really? AppleDataSetManagement is a signed kext. What exceptions are you talking about? And it works with SIP enabled as well.

**Comment by corpnewt** [comment]
Hmm - looks like it just throws "missing dependencies" errors instead of exceptions.  I may have been mistaken.  Pics for reference (using 10.12.6 beta forcing web drivers to load - hence the error there - and also Apple messed up their AppleMobileDevice somehow...):

![screen shot 2017-05-27 at 8 04 49 pm](https://cloud.githubusercontent.com/assets/12772521/26525263/6e1cc372-4318-11e7-8899-5a3f020cfac8.png)

![screen shot 2017-05-27 at 8 05 30 pm](https://cloud.githubusercontent.com/assets/12772521/26525272/89907126-4318-11e7-9d61-49f832307985.png)

![screen shot 2017-05-27 at 8 07 07 pm](https://cloud.githubusercontent.com/assets/12772521/26525273/90d436f2-4318-11e7-89c5-86c9b0ce4b95.png)

**Comment by vandroiy2013** [comment]
Anyway this kext is signed and work with SIP enabled. So i don't understand, if we talking about real macs why we have to use two unsigned kexts instead of one native to achieve our goal. As for hackintosh - Clover KextToPatch section in config.plist is the best way for this patch for systems under 10.10.3. From 10.10.4 sudo trimforce enable command is the easiest way for both hacks and real macs.

In my opinion this plugin is useless...

**Comment by vit9696** [comment]
AppleMobileDevice has a special signature, it had always been like that. As for nvidia, it is definitely your issue. Valid OSBundleCompatibleVersion is not an error. To be honest, I don't feel like making this a plugin. Bootloader patch or Apple's kext feel saner.

**Comment by corpnewt** [comment]
Yep, I just misremembered the output after trimforce. The nvidia error is
because I'm force-loading the 10.12.5 drivers on the 10.12.6 beta - so
that's to be expected. I was just giving my input because I thought it
threw an exception - but I was mistaken. Thanks!
